{% set name = "mosaic" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/mosaic/archive/{{ version }}.tar.gz
  sha256: 2908dad7df50789be7108a34520a6a4e5b49aad140877e755ece513d0b21c746

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - cartopy
    - cmocean
    - h5netcdf
    - netcdf4
    - matplotlib-base
    - numpy
    - pyproj
    - scipy
    - xarray

test:
  imports:
    - mosaic
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/mosaic/
  summary: Graphics package for MPAS meshes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.e3sm.org/mosaic/
  dev_url: https://github.com/E3SM-Project/mosaic/

extra:
  recipe-maintainers:
    - andrewdnolan
    - xylar
